name: Security CI (SAST + SCA + DAST)

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install "semgrep==1.36.0"

      - name: Run Semgrep and generate SARIF
        run: |
          semgrep --version
          # política padrão recomendada
          semgrep --config p/ci --sarif -o semgrep.sarif --timeout 0 || true
          test -s semgrep.sarif || (echo "semgrep.sarif não gerado" && exit 2)
